// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileDiffer
{
    static class Vsix
    {
        public const string Id = "714967d5-ee17-4bb1-a719-8cbf33d3bca9";
        public const string Name = "File Differ";
        public const string Description = @"The easiest way to diff two files directlty from Solution Explorer";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Luis Zamora";
        public const string Tags = "compare, diff, files";
    }
}
