// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileDiffer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidDiffFilesCommandPackageString = "6f9a828f-47e9-4e8e-b778-c27ac26ca966";
        public const string guidDiffFilesCommandPackageCmdSetString = "deb78c2c-c653-419a-902c-0cfc3391e4b4";
        public const string guidImagesString = "67b1eeac-2d18-4e09-8566-494447e69b2d";
        public static Guid guidDiffFilesCommandPackage = new Guid(guidDiffFilesCommandPackageString);
        public static Guid guidDiffFilesCommandPackageCmdSet = new Guid(guidDiffFilesCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int DiffFilesCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
